### PR TITLE
OpenTSDB backend support with tags

### PR DESCRIPTION
**Pull request by mikwat**
The StatsD [OpenTSDB backend](https://github.com/danslimmon/statsd-opentsdb-backend) supports tags in a different format than the existing Datadog implementation.

Feedback welcome @jstorimer @wvanbergen

### CODE REVIEW

**Comment by mikwat** [comment]
@jstorimer @wvanbergen Feedback welcome whenever you have a chance to look at this. Thanks.

**Comment by wvanbergen** [comment]
I'll try to look at this this week.

Note: at this point, it may make sense to start splitting up different implementations in different classes, instead of a bunch of if statements. This code is in a hot path (at least for us), and I rather run the if statement during initialization instead of every StatsD packet.

**Comment by mikwat** [comment]
That makes sense, @wvanbergen I might be able to take a pass at splitting it up.

**Comment by mikwat** [comment]
Hey @wvanbergen, I've split out the OpenTSDB logic into a separate class that inherits from `UDPBackend`. If you like this approach, maybe something similar could be done for the other implementations. What do you think?

**Pull request closed without merging**
